FROM node:18-alpine3.15 AS base

ARG URL=$1

FROM base AS installer
# Set working directory
WORKDIR /app
RUN npm -g i pnpm@8.6.10 turbo
COPY . .

WORKDIR /app
RUN pnpm install
RUN pnpm build --filter=shell

FROM installer AS runner
WORKDIR /app

# Don't run production as root
RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs
RUN chown nextjs:nodejs /app
USER nextjs

COPY --from=installer --chown=nextjs:nodejs /app/apps/shell/next.config.js .
COPY --from=installer --chown=nextjs:nodejs /app/apps/shell/package.json .

# Automatically leverage output traces to reduce image size
# https://nextjs.org/docs/advanced-features/output-file-tracing
COPY --from=installer --chown=nextjs:nodejs /app/apps/shell/.next/standalone /app/
COPY --from=installer --chown=nextjs:nodejs /app/shell.sh /app/shell.sh
COPY --from=installer --chown=nextjs:nodejs /app/apps/shell/.next/static ./apps/shell/.next/static

# CMD [ "node", "/app/apps/shell/server.js" ]
CMD [ "sh", "shell.sh" ]

