FROM node:18-alpine3.15 AS base

FROM base AS installer
# Set working directory
WORKDIR /app
RUN npm -g i pnpm@8.6.10 turbo
COPY . .

RUN pnpm install
RUN pnpm build --filter=web

FROM installer AS runner
WORKDIR /app

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs
RUN chown nextjs:nodejs /app
USER nextjs

COPY --chown=nextjs:nodejs apps/web/next.config.js .
COPY --chown=nextjs:nodejs apps/web/package.json .

# Automatically leverage output traces to reduce image size
# https://nextjs.org/docs/advanced-features/output-file-tracing
# COPY --chown=nextjs:nodejs apps/web/.next/standalone /app/standalone
# COPY --chown=nextjs:nodejs apps/web/.next/static ./apps/web/.next/static

CMD node apps/web/server.js
