FROM node:18-alpine3.15 AS base

ARG URL=$1

FROM base AS installer
# Set working directory
WORKDIR /app
RUN npm -g i pnpm@8.6.10 turbo
COPY . .

RUN pnpm install
RUN pnpm build --filter=shell

FROM installer AS runner
WORKDIR /app

# RUN addgroup --system --gid 1001 nodejs
# RUN adduser --system --uid 1001 nextjs
# RUN chown nextjs:nodejs /app

RUN addgroup --system --gid 1001 nodejs \
    && adduser --system --uid 1001 nextjs \
    && chown nextjs:nodejs /app \
    && find /app -type d -name 'node_modules' -prune -o -exec chown nextjs:nodejs {} + \
    && find /app/apps/shell/next.config.js -exec chown nextjs:nodejs {} + \
    && find /app/apps/shell/.next/standalone/apps/shell/.next/server/webpack-runtime.js -exec chown nextjs:nodejs {} + \
    && find /app/apps/shell/.next/server/webpack-runtime.js -exec chown nextjs:nodejs {} + \
    && find /app/apps/shell/.next/static/chunks/pages -exec chown -R nextjs:nodejs {} + \
    && find /app/apps/shell/.next/static/ssr/remoteEntry.js -exec chown nextjs:nodejs {} +

COPY --chown=nextjs:nodejs apps/shell/next.config.js ./apps/shell/next.config.js
COPY --chown=nextjs:nodejs apps/shell/package.json ./apps/shell/package.json


# Automatically leverage output traces to reduce image size
# https://nextjs.org/docs/advanced-features/output-file-tracing
# COPY --chown=nextjs:nodejs apps/shell/.next/standalone /app/standalone
# COPY --chown=nextjs:nodejs apps/shell/.next/static ./apps/shell/.next/static
COPY --chown=nextjs:nodejs shell.sh /app/shell.sh

USER nextjs

CMD [ "sh", "shell.sh" ]

